using Microsoft.EntityFrameworkCore;
using PaladinHubV2.Server.Data.Entities;
using PaladinHubV2.Server.Data.Seed.Contracts;
using Microsoft.Extensions.DependencyInjection;

namespace PaladinHubV2.Server.Data.Seed;

public class SpellbookSeeder : ISeeder
	{
		private readonly IServiceProvider _sp;
		public SpellbookSeeder(IServiceProvider sp) => _sp = sp;

		public async Task SeedAsync()
		{
			using var scope = _sp.CreateScope();
			var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

			if (await db.Spells.AnyAsync()) return;

			var spells = new[]
			{
			new Spell { Id =1, Name ="A Just Reward", Icon = "A Just Reward.jpg", Url = "https://www.wowhead.com/spell=469411/a-just-reward", Description = "Protection,  Retribution After Cleanse Toxins successfully removes an effect from an ally, they are healed for (540% of Spell power). Holy After Cleanse successfully removes an effect from an ally, they are healed for (540% of Spell power)."},
			new Spell { Id =2, Name ="Adjudication", Icon = "Ardent Defender.jpg", Url = "https://www.wowhead.com/spell=406157/adjudication", Description = "Critical Strike damage of your abilities increased by 5% and Hammer of Wrath also has a chance to cast Highlord's Judgment."},
			new Spell { Id =3, Name ="Aegis of Light", Icon = "Ashes to Ashes.jpg", Url = "https://www.wowhead.com/spell=204150/aegis-of-light", Description = "Channels an Aegis of Light that protects you and all allies standing within 10 yards behind you for 6 sec, reducing all damage taken by 20%."},
			new Spell { Id =4, Name ="Aegis of Protection", Icon = "Aura Mastery.jpg", Url = "https://www.wowhead.com/spell=403654/aegis-of-protection", Description = "Divine Protection reduces damage you take by an additional 20%."},
			new Spell { Id =5, Name ="Afterimage", Icon = "Moment of Glory.jpg", Url = "https://www.wowhead.com/spell=385414/afterimage", Description = "After you spend 20 Holy Power, your next Word of Glory echoes onto a nearby ally at 30% effectiveness."},
			new Spell { Id =6, Name ="Ardent Defender", Icon = "Ardent Defender.jpg", Url = "https://www.wowhead.com/spell=31850/ardent-defender", Description = " Reduces all damage you take by 20% for 8 sec. While Ardent Defender is active, the next attack that would otherwise kill you will instead bring you to 20% of your maximum health."},
			new Spell { Id =7, Name ="Ashes to Ashes", Icon = "Awakening.jpg", Url = "https://www.wowhead.com/spell=405607/ashes-to-ashes", Description = ""},
			new Spell { Id =8, Name ="Aura Mastery", Icon = "Aura Mastery.jpg", Url = "https://www.wowhead.com/spell=31821/aura-mastery", Description = ""},
			new Spell { Id =9, Name ="Auras of the Resolute", Icon = "Devotion Aura.jpg", Url = "https://www.wowhead.com/spell=385633/auras-of-the-resolute", Description = ""},
			new Spell { Id =10, Name ="Aurora", Icon = "Breaking Dawn.jpg", Url = "https://www.wowhead.com/spell=439760/aurora", Description = " "},
			new Spell { Id =11, Name ="Authoritative Rebuke", Icon = "Authoritative Rebuke.jpg", Url = "https://www.wowhead.com/spell=469886/authoritative-rebuke", Description = "Successfully interrupting an enemy spellcast reduces your Rebuke's cooldown by 1.0 sec. Effect increased by 100% while wielding a Holy Armament."},
			new Spell { Id =12, Name ="Avenger's Shield", Icon = "Avengers Shield.jpg", Url = "https://www.wowhead.com/spell=31935/avengers-shield", Description = ""},
			new Spell { Id =13, Name ="Avenging Crusader", Icon = "Bestow Faith.jpg", Url = "https://www.wowhead.com/spell=216331/avenging-crusader", Description = " "},
			new Spell { Id =14, Name ="Avenging Wrath", Icon = "Avenging Wrath.jpg", Url = "https://www.wowhead.com/spell=31884/avenging-wrath", Description = ""},
			new Spell { Id =15, Name ="Avenging Wrath1", Icon = "Blades of Light.jpg", Url = "https://www.wowhead.com/spell=31884/avenging-wrath", Description = ""},
			new Spell { Id =16, Name ="Avenging Wrath2", Icon = "Merciful Auras.jpg", Url = "https://www.wowhead.com/spell=327979/avenging-wrath", Description = ""},
			new Spell { Id =17, Name ="Awakening", Icon = "Awakening.jpg", Url = "https://www.wowhead.com/spell=248033/awakening", Description = " "},
			new Spell { Id =18, Name ="Awakening2", Icon = "Awakening.jpg", Url = "https://www.wowhead.com/spell=414195/awakening", Description = " "},
			new Spell { Id =19, Name ="Awestruck", Icon = "Awestruck.jpg", Url = "https://www.wowhead.com/spell=417855/awestruck", Description = ""},
			new Spell { Id =20, Name ="Barricade of Faith", Icon = "Barrier of Faith.jpg", Url = "https://www.wowhead.com/spell=385726/barricade-of-faith", Description = ""},
			new Spell { Id =21, Name ="Barrier of Faith", Icon = "Barrier of Faith.jpg", Url = "https://www.wowhead.com/spell=148039/barrier-of-faith", Description = " "},
			new Spell { Id =22, Name ="Barrier of Faith2", Icon = "Beacon of Faith.jpg", Url = "https://www.wowhead.com/spell=148039/barrier-of-faith", Description = ""},
			new Spell { Id =23, Name ="Bastion of Light", Icon = "Bastion of Light.jpg", Url = "https://www.wowhead.com/spell=378974/bastion-of-light", Description = ""},
			new Spell { Id =24, Name ="Beacon of Faith", Icon = "Beacon of Faith.jpg", Url = "https://www.wowhead.com/spell=156910/beacon-of-faith", Description = " "},
			new Spell { Id =25, Name ="Beacon of Light", Icon = "Beacon of Light.jpg", Url = "https://www.wowhead.com/spell=53563/beacon-of-light", Description = " "},
			new Spell { Id =26, Name ="Beacon of Light1", Icon = "Beacon of Light.jpg", Url = "https://www.wowhead.com/spell=53563/beacon-of-light", Description = " "},
			new Spell { Id =27, Name ="Beacon of the Lightbringer", Icon = "Lightbearer.jpg", Url = "https://www.wowhead.com/spell=197446/beacon-of-the-lightbringer", Description = " "},
			new Spell { Id =28, Name ="Beacon of Virtue", Icon = "Beacon of Virtue.jpg", Url = "https://www.wowhead.com/spell=200025/beacon-of-virtue", Description = ""},
			new Spell { Id =29, Name ="Beacon of Virtue2", Icon = "Beacon of Virtue.jpg", Url = "https://www.wowhead.com/spell=200025/beacon-of-virtue", Description = ""},
			new Spell { Id =30, Name ="Beacon of Virtue3", Icon = "Beacon of Virtue.jpg", Url = "https://www.wowhead.com/spell=200025/beacon-of-virtue", Description = ""},
			new Spell { Id =31, Name ="Bestow Faith", Icon = "Bestow Faith.jpg", Url = "https://www.wowhead.com/spell=223306/bestow-faith", Description = ""},
			new Spell { Id =32, Name ="Bestow Light", Icon = "Empyrean Power.jpg", Url = "https://www.wowhead.com/spell=448040/bestow-light", Description = "Light of the Martyr's health threshold is reduced to 70% and increases Holy Shock's healing by an additional 5% for every 5 sec Light of the Martyr is active, stacking up to 3 times.While below 70% health, the light urgently heals you for (20 % of Spell power) every 1 sec."},
			new Spell { Id =33, Name ="Blade of Justice", Icon = "Blade of Justice.jpg", Url = "https://www.wowhead.com/spell=184575/blade-of-justice", Description = ""},
			new Spell { Id =34, Name ="Blade of Justice2", Icon = "Blade of Justice.jpg", Url = "https://www.wowhead.com/spell=184575/blade-of-justice", Description = ""},
			new Spell { Id =35, Name ="Blade of Vengeance", Icon = "Blade of Justice.jpg", Url = "https://www.wowhead.com/spell=403826/blade-of-vengeance", Description = ""},
			new Spell { Id =36, Name ="Blade of Vengeance2", Icon = "Blade of Justice.jpg", Url = "https://www.wowhead.com/spell=403826/blade-of-vengeance", Description = ""},
			new Spell { Id =37, Name ="Blade of Wrath", Icon = "Blade of Wrath.jpg", Url = "https://www.wowhead.com/spell=231832/blade-of-wrath", Description = ""},
			new Spell { Id =38, Name ="Blades of Light", Icon = "Blades of Light.jpg", Url = "https://www.wowhead.com/spell=403664/blades-of-light", Description = "[Templar Strikes: Templar Strikes] [Crusading Strikes: Crusading Strikes / Crusader Strike, ]Judgment, Hammer of Wrath and your damaging single target Holy Power abilities now deal Holystrike damage and your abilities that deal Holystrike damage deal 5% increased damage."},
			new Spell { Id =39, Name ="Blessed Assurance", Icon = "Merciful Auras.jpg", Url = "https://www.wowhead.com/spell=433015/blessed-assurance", Description = ""},
			new Spell { Id =40, Name ="Blessed Calling", Icon = "Blessed Calling.jpg", Url = "https://www.wowhead.com/spell=469770/blessed-calling", Description = " "},
			new Spell { Id =41, Name ="Blessed Champion", Icon = "Blessed Champion.jpg", Url = "https://www.wowhead.com/spell=403010/blessed-champion", Description = " "},
			new Spell { Id =42, Name ="Blessed Focus", Icon = "Blessed Focus.jpg", Url = "https://www.wowhead.com/spell=414289/blessed-focus", Description = " "},
			new Spell { Id =43, Name ="Blessed Focus2", Icon = "Blessing of Autumn.jpg", Url = "https://www.wowhead.com/spell=414289/blessed-focus", Description = " "},
			new Spell { Id =44, Name ="Blessed Hammer", Icon = "Blessed Hammer.jpg", Url = "https://www.wowhead.com/spell=204019/blessed-hammer", Description = ""},
			new Spell { Id =45, Name ="Blessed Hands", Icon = "Blessed Hands.jpg", Url = "https://www.wowhead.com/spell=379391/blessed-hands", Description = ""},
			new Spell { Id =46, Name ="Blessing of An'she", Icon = "Blessing of Anshe.jpg", Url = "https://www.wowhead.com/spell=445200/blessing-of-anshe", Description = " "},
			new Spell { Id =47, Name ="Blessing of Autumn", Icon = "Blessing of Spring.jpg", Url = "https://www.wowhead.com/spell=388010/blessing-of-autumn", Description = ""},
			new Spell { Id =48, Name ="Blessing of Freedom", Icon = "Blessing of Freedom.jpg", Url = "https://www.wowhead.com/spell=1044/blessing-of-freedom", Description = " "},
			new Spell { Id =49, Name ="Blessing of Protection", Icon = "Blessing of Protection.jpg", Url = "https://www.wowhead.com/spell=1022/blessing-of-protection", Description = " "},
			new Spell { Id =50, Name ="Blessing of Sacrifice", Icon = "Blessing of Sacrifice.jpg", Url = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice", Description = ""},
			new Spell { Id =51, Name ="Blessing of Sacrifice2", Icon = "Blessing of Sacrifice.jpg", Url = "https://www.wowhead.com/spell=6940/blessing-of-sacrifice", Description = ""},
			new Spell { Id =52, Name ="Blessing of Spellwarding", Icon = "Blessing of Spellwarding.jpg", Url = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding", Description = " "},
			new Spell { Id =53, Name ="Blessing of Spellwarding2", Icon = "Blessing of Spellwarding.jpg", Url = "https://www.wowhead.com/spell=204018/blessing-of-spellwarding", Description = " "},
			new Spell { Id =54, Name ="Blessing of Spring", Icon = "Blessing of Summer.jpg", Url = "https://www.wowhead.com/spell=388013/blessing-of-spring", Description = ""},
			new Spell { Id =55, Name ="Blessing of Summer", Icon = "Blessing of Summer.jpg", Url = "https://www.wowhead.com/spell=388007/blessing-of-summer", Description = " "},
			new Spell { Id =56, Name ="Blessing of Summer2", Icon = "Blessing of Winter.jpg", Url = "https://www.wowhead.com/spell=388007/blessing-of-summer", Description = ""},
			new Spell { Id =57, Name ="Blessing of the Forge", Icon = "Blessing of the Forge.jpg", Url = "https://www.wowhead.com/spell=433011/blessing-of-the-forge", Description = ""},
			new Spell { Id =58, Name ="Blessing of Winter", Icon = "Boundless Salvation.jpg", Url = "https://www.wowhead.com/spell=388011/blessing-of-winter", Description = ""},
			new Spell { Id =59, Name ="Blinding Light", Icon = "Blinding Light.jpg", Url = "https://www.wowhead.com/spell=115750/blinding-light", Description = " "},
			new Spell { Id =60, Name ="Boundless Salvation", Icon = "Boundless Salvation.jpg", Url = "https://www.wowhead.com/spell=392951/boundless-salvation", Description = ""},
			new Spell { Id =61, Name ="Boundless Salvation2", Icon = "Boundless Salvation.jpg", Url = "https://www.wowhead.com/spell=392951/boundless-salvation", Description = " "},
			new Spell { Id =62, Name ="Breaking Dawn", Icon = "Breaking Dawn.jpg", Url = "https://www.wowhead.com/spell=409673/breaking-dawn", Description = ""},
			new Spell { Id =63, Name ="Bulwark of Order", Icon = "Bulwark of Order.jpg", Url = "https://www.wowhead.com/spell=209389/bulwark-of-order", Description = ""},
			new Spell { Id =64, Name ="Bulwark of Righteous Fury", Icon = "Bulwark of Righteous Fury.jpg", Url = "https://www.wowhead.com/spell=386653/bulwark-of-righteous-fury", Description = ""},
			new Spell { Id =65, Name ="Burn to Ash", Icon = "Burn to Ash.jpg", Url = "https://www.wowhead.com/spell=446663/burn-to-ash", Description = ""},
			new Spell { Id =66, Name ="Burning Crusade", Icon = "Burning Crusade.jpg", Url = "https://www.wowhead.com/spell=406545/burning-crusade", Description = " "},
			new Spell { Id =67, Name ="Burning Vengeance", Icon = "Burning Vengeance.jpg", Url = "https://www.wowhead.com/spell=406646/burning-vengeance", Description = " "},
			new Spell { Id =68, Name ="Cavalier", Icon = "Divine Steed.jpg", Url = "https://www.wowhead.com/spell=230332/cavalier", Description = ""},
			new Spell { Id =69, Name ="Cleanse", Icon = "Cleanse.jpg", Url = "https://www.wowhead.com/spell=4987/cleanse", Description = ""},
			new Spell { Id =70, Name ="Cleanse Toxins", Icon = "Cleanse Toxins.jpg", Url = "https://www.wowhead.com/spell=213644/cleanse-toxins", Description = " "},
			new Spell { Id =71, Name ="Commanding Light", Icon = "Beacon of Light.jpg", Url = "https://www.wowhead.com/spell=387781/commanding-light", Description = " "},
			new Spell { Id =72, Name ="Consecrated Ground", Icon = "Consecrated Ground.jpg", Url = "https://www.wowhead.com/spell=204054/consecrated-ground", Description = ""},
			new Spell { Id =73, Name ="Consecration", Icon = "Consecration.jpg", Url = "https://www.wowhead.com/spell=26573/consecration", Description = ""},
			new Spell { Id =74, Name ="Consecration in Flame", Icon = "Burning Crusade.jpg", Url = "https://www.wowhead.com/spell=379022/consecration-in-flame", Description = ""},
			new Spell { Id =75, Name ="Crusade", Icon = "Crusade.jpg", Url = "https://www.wowhead.com/spell=231895/crusade", Description = ""},
			new Spell { Id =76, Name ="Crusade2", Icon = "Crusade.jpg", Url = "https://www.wowhead.com/spell=231895/crusade", Description = ""},
			new Spell { Id =77, Name ="Crusader Strike", Icon = "Fires of Justice.jpg", Url = "https://www.wowhead.com/spell=35395/crusader-strike", Description = " "},
			new Spell { Id =78, Name ="Crusader's Judgment", Icon = "Crusaders Judgment.jpg", Url = "https://www.wowhead.com/spell=204023/crusaders-judgment", Description = " "},
			new Spell { Id =79, Name ="Crusader's Might", Icon = "Crusaders Might.jpg", Url = "https://www.wowhead.com/spell=196926/crusaders-might", Description = ""},
			new Spell { Id =80, Name ="Crusader's Reprieve", Icon = "Crusader's Reprieve.jpg", Url = "https://www.wowhead.com/spell=403010/crusaders-reprieve", Description = " "},
			new Spell { Id =81, Name ="Crusader's Resolve", Icon = "Crusader's Resolve.jpg", Url = "https://www.wowhead.com/spell=380188/crusaders-resolve", Description = ""},
			new Spell { Id =82, Name ="Crusader's Resolve2", Icon = "Daybreak.jpg", Url = "https://www.wowhead.com/spell=380188/crusaders-resolve", Description = ""},
			new Spell { Id =83, Name ="Crusading Strikes", Icon = "Crusading Strikes.jpg", Url = "https://www.wowhead.com/spell=404542/crusading-strikes", Description = ""},
			new Spell { Id =84, Name ="Dawnlight", Icon = "Dawnlight.jpg", Url = "https://www.wowhead.com/spell=431377/dawnlight", Description = ""},
			new Spell { Id =85, Name ="Daybreak", Icon = "Daybreak.jpg", Url = "https://www.wowhead.com/spell=414293/daybreak", Description = " "},
			new Spell { Id =86, Name ="Daybreak2", Icon = "Daybreak.jpg", Url = "https://www.wowhead.com/spell=414293/daybreak", Description = ""},
			new Spell { Id =87, Name ="Daybreak3", Icon = "Divine Glimpse.jpg", Url = "https://www.wowhead.com/spell=414293/daybreak", Description = " "},
			new Spell { Id =88, Name ="Devotion Aura", Icon = "Devotion Aura", Url = "https://www.wowhead.com/spell=465/devotion-aura", Description = ""},
			new Spell { Id =89, Name ="Divine Allegiance", Icon = "Divine Allegiance.jpg", Url = "https://www.wowhead.com/spell=406788/divine-allegiance", Description = " "},
			new Spell { Id =90, Name ="Divine Arbiter", Icon = "Divine Arbiter.jpg", Url = "https://www.wowhead.com/spell=406251/divine-arbiter", Description = ""},
			new Spell { Id =91, Name ="Divine Call", Icon = "Divine Call.jpg", Url = "https://www.wowhead.com/spell=403566/divine-call", Description = " "},
			new Spell { Id =92, Name ="Divine Favor", Icon = "Divine Favor.jpg", Url = "https://www.wowhead.com/spell=210294/divine-favor", Description = "The healing of your next Holy Light or Flash of Light is increased by 20%, its cast time is reduced by 30%, and its mana cost is reduced by 50%."},
			new Spell { Id =93, Name ="Divine Glimpse", Icon = "Divine Glimpse.jpg", Url = "https://www.wowhead.com/spell=387805/divine-glimpse", Description = ""},
			new Spell { Id =94, Name ="Divine Guidance", Icon = "Divine Guidance.jpg", Url = "https://www.wowhead.com/spell=433106/divine-guidance", Description = " "},
			new Spell { Id =95, Name ="Divine Hammer", Icon = "Divine Hammer.jpg", Url = "https://www.wowhead.com/spell=198034/divine-hammer", Description = " "},
			new Spell { Id =96, Name ="Divine Inspiration", Icon = "Divine Inspiration.jpg", Url = "https://www.wowhead.com/spell=432964/divine-inspiration", Description = ""},
			new Spell { Id =97, Name ="Divine Judgement", Icon = "Divine Judgement.jpg", Url = "https://www.wowhead.com/spell=448515/divine-judgment", Description = ""},
			new Spell { Id =98, Name ="Divine Protection", Icon = "Divine Reach.jpg", Url = "https://www.wowhead.com/spell=498/divine-protection", Description = " "},
			new Spell { Id =99, Name ="Divine Purpose", Icon = "Divine Purpose.jpg", Url = "https://www.wowhead.com/spell=223819/divine-purpose", Description = "Holy Power spending abilities have a 15% chance to make your next Holy Power spending ability free and deal 15% increased damage and healing."},
			new Spell { Id =100, Name ="Divine Purpose (Retribution)", Icon = "Divine Purpose (Retribution).jpg", Url = "https://www.wowhead.com/spell=223819/divine-purpose", Description = " "},
			new Spell { Id =101, Name ="Divine Purpose2", Icon = "Divine Purpose.jpg", Url = "https://www.wowhead.com/spell=408459/divine-purpose", Description = "Holy Power spending abilities have a 10% chance to make your next Holy Power spending ability free and deal 10% increased damage and healing."},
			new Spell { Id =102, Name ="Divine Reach", Icon = "Relentless Inquisitor.jpg", Url = "https://www.wowhead.com/spell=469476/divine-reach", Description = ""},
			new Spell { Id =103, Name ="Divine Resonance", Icon = "Divine Resonance.jpg", Url = "https://www.wowhead.com/spell=384027/divine-resonance", Description = ""},
			new Spell { Id =104, Name ="Divine Resonance2", Icon = "Divine Resonance.jpg", Url = "https://www.wowhead.com/spell=386738/divine-resonance", Description = ""},
			new Spell { Id =105, Name ="Divine Revelation", Icon = "Divine Revelation.jpg", Url = "https://www.wowhead.com/spell=387808/divine-revelations", Description = ""},
			new Spell { Id =106, Name ="Divine Revelations", Icon = "Healing Hands.jpg", Url = "https://www.wowhead.com/spell=387808/divine-revelations", Description = ""},
			new Spell { Id =107, Name ="Divine Shield", Icon = "Divine Shield.jpg", Url = "https://www.wowhead.com/spell=642/divine-shield", Description = " "},
			new Spell { Id =108, Name ="Divine Spurs", Icon = "Divine Spurs.jpg", Url = "https://www.wowhead.com/spell=469409/divine-spurs", Description = ""},
			new Spell { Id =109, Name ="Divine Steed", Icon = "Divine Steed.jpg", Url = "https://www.wowhead.com/spell=190784/divine-steed", Description = ""},
			new Spell { Id =110, Name ="Divine Storm", Icon = "Divine Storm.jpg", Url = "https://www.wowhead.com/spell=53385/divine-storm", Description = ""},
			new Spell { Id =111, Name ="Divine Toll", Icon = "Divine Toll.jpg", Url = "https://www.wowhead.com/spell=375576/divine-toll", Description = " "},
			new Spell { Id =112, Name ="Divine Toll2", Icon = "Lay on Hands.jpg", Url = "https://www.wowhead.com/spell=375576/divine-toll", Description = " "},
			new Spell { Id =113, Name ="Divine Wrath", Icon = "Divine Wrath.jpg", Url = "https://www.wowhead.com/spell=406872/divine-wrath", Description = ""},
			new Spell { Id =114, Name ="Echoing Blessings", Icon = "Echoing Blessings.jpg", Url = "https://www.wowhead.com/spell=387801/echoing-blessings", Description = "Blessing of Freedom increases the target's movement speed by 30%. [Blessing of Spellwarding / Blessing of Protection] and Blessing of Sacrifice reduce the target's damage taken by 15%. These effects linger for 8 sec after the Blessing ends."},
			new Spell { Id =115, Name ="Empyreal Ward", Icon = "Lay on Hands.jpg", Url = "https://www.wowhead.com/spell=387791/empyreal-ward", Description = "Lay on Hands grants the target 30% increased armor for 8 sec and now ignores healing reduction effects."},
			new Spell { Id =116, Name ="Empyrean Legacy", Icon = "Empyrean Legacy.jpg", Url = "https://www.wowhead.com/spell=387998/empyrean-legacy", Description = ""},
			new Spell { Id =117, Name ="Empyrean Legacy2", Icon = "Faiths Armor.jpg", Url = "https://www.wowhead.com/spell=387998/empyrean-legacy", Description = " "},
			new Spell { Id =118, Name ="Empyrean Power", Icon = "Empyrean Power.jpg", Url = "https://www.wowhead.com/spell=286392/empyrean-power", Description = ""},
			new Spell { Id =119, Name ="Eternal Flame", Icon = "Eternal Flame.jpg", Url = "https://www.wowhead.com/spell=114163/eternal-flame", Description = " "},
			new Spell { Id =120, Name ="Execution Sentence", Icon = "Execution Sentence.jpg", Url = "https://www.wowhead.com/spell=343527/execution-sentence", Description = ""},
			new Spell { Id =121, Name ="Executioner's Will", Icon = "Executioners Will.jpg", Url = "https://www.wowhead.com/spell=406940/executioners-will", Description = " "},
			new Spell { Id =122, Name ="Expurgation", Icon = "Expurgation.jpg", Url = "https://www.wowhead.com/spell=273476/expurgation", Description = " " },
			new Spell { Id =123, Name ="Expurgation2", Icon = "Expurgation.jpg", Url = "https://www.wowhead.com/spell=383344/expurgation", Description = ""},
			new Spell { Id =124, Name ="Extrication", Icon = "Extrication.jpg", Url = "https://www.wowhead.com/spell=461278/extrication", Description = ""},
			new Spell { Id =125, Name ="Eye for an Eye", Icon = "Divine Arbiter.jpg", Url = "https://www.wowhead.com/spell=469309/eye-for-an-eye", Description = " "},
			new Spell { Id =126, Name ="Eye for an Eye2", Icon = "Eye for an Eye.jpg", Url = "https://www.wowhead.com/spell=205191/eye-for-an-eye", Description = " "},
			new Spell { Id =127, Name ="Eye of Tyr", Icon = "Eye of Tyr.jpg", Url = "https://www.wowhead.com/spell=387174/eye-of-tyr", Description = " "},
			new Spell { Id =128, Name ="Faith in the Light", Icon = "Faith in the Light.jpg", Url = "https://www.wowhead.com/spell=379043/faith-in-the-light", Description = " "},
			new Spell { Id =129, Name ="Faith's Armor", Icon = "Faiths Armor.jpg", Url = "https://www.wowhead.com/spell=406101/faiths-armor", Description = " "},
			new Spell { Id =130, Name ="Faith's Reward", Icon = "Faith's Reward.jpg", Url = "https://www.wowhead.com/spell=385349/faiths-reward", Description = ""},
			new Spell { Id =131, Name ="Ferren Marcus's Fervor", Icon = "Seal of Might.jpg", Url = "https://www.wowhead.com/spell=378762/ferren-marcuss-fervor", Description = " "},
			new Spell { Id =132, Name ="Final Reckoning", Icon = "Final Reckoning.jpg", Url = "https://www.wowhead.com/spell=343721/final-reckoning", Description = " "},
			new Spell { Id =133, Name ="Final Stand", Icon = "Final Stand.jpg", Url = "https://www.wowhead.com/spell=204077/final-stand", Description = " "},
			new Spell { Id =134, Name ="Final Verdict", Icon = "Final Verdict.jpg", Url = "https://www.wowhead.com/spell=383328/final-verdict", Description = " "},
			new Spell { Id =135, Name ="Fires of Justice", Icon = "Fires of Justice.jpg", Url = "https://www.wowhead.com/spell=203316/fires-of-justice", Description = ""},
			new Spell { Id =136, Name ="First Avenger", Icon = "Flash of Light.jpg", Url = "https://www.wowhead.com/spell=203776/first-avenger", Description = "Avenger's Shield hits 2 additional targets,  and grants you an absorb shield for 100% of all damage it deals."},
			new Spell { Id =137, Name ="Fist of Justice", Icon = "Fist of Justice.jpg", Url = "https://www.wowhead.com/spell=234299/fist-of-justice", Description = " "},
			new Spell { Id =138, Name ="Flash of Light", Icon = "Flash of Light.jpg", Url = "https://www.wowhead.com/spell=19750/flash-of-light", Description = ""},
			new Spell { Id =139, Name ="Focused Enmity", Icon = "Divine Inspiration.jpg", Url = "https://www.wowhead.com/spell=378845/focused-enmity", Description = ""},
			new Spell { Id =140, Name ="Focused Enmity2", Icon = "Glistening Radiance.jpg", Url = "https://www.wowhead.com/spell=378845/focused-enmity", Description = ""},
			new Spell { Id =141, Name ="For Whom the Bell Tolls", Icon = "Hammer of the Righteous.jpg", Url = "https://www.wowhead.com/spell=432929/for-whom-the-bell-tolls", Description = "Divine Toll grants up to 100% increased damage to your next 3 Judgment when striking only 1 enemy. This amount is reduced by 20% for each additional target struck."},
			new Spell { Id =142, Name ="Gift of the Golden Val'kyr", Icon = "Gift of the Golden Valkyr.jpg", Url = "https://www.wowhead.com/spell=378279/gift-of-the-golden-valkyr", Description = " "},
			new Spell { Id =143, Name ="Gleaming Rays", Icon = "Gleaming Rays.jpg", Url = "https://www.wowhead.com/spell=431480/gleaming-rays", Description = ""},
			new Spell { Id =144, Name ="Glimmer of Light", Icon = "Shining Light.jpg", Url = "https://www.wowhead.com/spell=287269/glimmer-of-light", Description = " "},
			new Spell { Id =145, Name ="Glistening Radiance", Icon = "Glistening Radiance.jpg", Url = "https://www.wowhead.com/spell=409647/glistening-radiance", Description = " "},
			new Spell { Id =146, Name ="Glistening Radiance2", Icon = "Glorious Dawn.jpg", Url = "https://www.wowhead.com/spell=409647/glistening-radiance", Description = " "},
			new Spell { Id =147, Name ="Glorious Dawn", Icon = "Suns Avatar.jpg", Url = "https://www.wowhead.com/spell=414387/glorious-dawn", Description = ""},
			new Spell { Id =148, Name ="Glorious Dawn2", Icon = "Greater Judgment.jpg", Url = "https://www.wowhead.com/spell=414387/glorious-dawn", Description = " "},
			new Spell { Id =149, Name ="Golden Path", Icon = "Golden Path.jpg", Url = "https://www.wowhead.com/spell=386916/golden-path", Description = ""},
			new Spell { Id =150, Name ="Golden Path (Prot)", Icon = "Golden Path (Prot).jpg", Url = "https://www.wowhead.com/spell=386916/golden-path", Description = ""},
			new Spell { Id =151, Name ="Grand Crusader", Icon = "Grand Crusader.jpg", Url = "https://www.wowhead.com/spell=85043/grand-crusader", Description = ""},
			new Spell { Id =152, Name ="Greater Judgment", Icon = "Judgment.jpg", Url = "https://www.wowhead.com/spell=385639/greater-judgment", Description = " "},
			new Spell { Id =153, Name ="Greater Judgment2", Icon = "Holy Light.jpg", Url = "https://www.wowhead.com/spell=385639/greater-judgment", Description = ""},
			new Spell { Id =154, Name ="Guardian of Ancient Kings", Icon = "Guardian of Ancient Kings.jpg", Url = "https://www.wowhead.com/spell=86659/guardian-of-ancient-kings", Description = ""},
			new Spell { Id =155, Name ="Hammer and Anvil", Icon = "Hammer and Anvil.jpg", Url = "https://www.wowhead.com/spell=433718/hammer-and-anvil", Description = ""},
			new Spell { Id =156, Name ="Hammer of Justice", Icon = "Hammer of Justice.jpg", Url = "https://www.wowhead.com/spell=853/hammer-of-justice", Description = " "},
			new Spell { Id =157, Name ="Hammer of the Righteous", Icon = "Hammer of the Righteous.jpg", Url = "https://www.wowhead.com/spell=53595/hammer-of-the-righteous", Description = " "},
			new Spell { Id =158, Name ="Hammer of Wrath", Icon = "Hammer of Wrath.jpg", Url = "https://www.wowhead.com/spell=24275/hammer-of-wrath", Description = " "},
			new Spell { Id =159, Name ="Hammerfall", Icon = "Crusaders Judgment.jpg", Url = "https://www.wowhead.com/spell=432463/hammerfall", Description = ""},
			new Spell { Id =160, Name ="Hand of Divinity", Icon = "Hand of Divinity.jpg", Url = "https://www.wowhead.com/spell=414273/hand-of-divinity", Description = ""},
			new Spell { Id =161, Name ="Hand of the Protector", Icon = "Power of the Silver Hand.jpg", Url = "https://www.wowhead.com/spell=315341/hand-of-the-protector", Description = ""},
			new Spell { Id =162, Name ="Healing Hands", Icon = "Healing Hands.jpg", Url = "https://www.wowhead.com/spell=326734/healing-hands", Description = " "},
			new Spell { Id =163, Name ="Higher Calling", Icon = "Shining Light.jpg", Url = "https://www.wowhead.com/spell=431687/higher-calling", Description = "Retribution Crusader Strike, Hammer of Wrath and Blade of Justice extend the duration of Shake the Heavens by 1 sec. Protection Crusader Strike, Hammer of Wrath and Judgment extend the duration of Shake the Heavens by 1 sec."},
			new Spell { Id =164, Name ="Highlord's Judgment", Icon = "Highlord's Judgment.jpg", Url = "https://www.wowhead.com/spell=405757/highlords-judgment", Description = " "},
			new Spell { Id =165, Name ="Highlord's Wrath", Icon = "Highlords Wrath.jpg", Url = "https://www.wowhead.com/spell=405779/highlords-wrath", Description = ""},
			new Spell { Id =166, Name ="Holy Aegis", Icon = "Holy Aegis.jpg", Url = "https://www.wowhead.com/spell=379008/holy-aegis", Description = ""},
			new Spell { Id =167, Name ="Holy Avenger", Icon = "Suns Avatar.jpg", Url = "https://www.wowhead.com/spell=105809/holy-avenger", Description = ""},
			new Spell { Id =168, Name ="Holy Blade", Icon = "Holy Blade.jpg", Url = "https://www.wowhead.com/spell=406158/holy-blade", Description = ""},
			new Spell { Id =169, Name ="Holy Bulwark", Icon = "Holy Bulwark.jpg", Url = "https://www.wowhead.com/spell=432459/holy-bulwark", Description = " "},
			new Spell { Id =170, Name ="Holy Flames", Icon = "Holy Flames.jpg", Url = "https://www.wowhead.com/spell=406545/holy-flames", Description = " "},
			new Spell { Id =171, Name ="Holy Light", Icon = "Holy Light.jpg", Url = "https://www.wowhead.com/spell=82326/holy-light", Description = " "},
			new Spell { Id =172, Name ="Holy Light2", Icon = "Holy Prism.jpg", Url = "https://www.wowhead.com/spell=82326/holy-light", Description = ""},
			new Spell { Id =173, Name ="Holy Prism", Icon = "Holy Prism.jpg", Url = "https://www.wowhead.com/spell=114165/holy-prism", Description = " "},
			new Spell { Id =174, Name ="Holy Prism2", Icon = "Holy Radiance.jpg", Url = "https://www.wowhead.com/spell=114165/holy-prism", Description = ""},
			new Spell { Id =175, Name ="Holy Radiance", Icon = "Holy Reprieve.jpg", Url = "https://www.wowhead.com/spell=82327/holy-radiance", Description = " "},
			new Spell { Id =176, Name ="Holy Reprieve", Icon = "Holy Reprieve.jpg", Url = "https://www.wowhead.com/spell=469445/holy-reprieve", Description = " "},
			new Spell { Id =177, Name ="Holy Ritual", Icon = "Holy Ritual.jpg", Url = "https://www.wowhead.com/spell=199422/holy-ritual", Description = " "},
			new Spell { Id =178, Name ="Holy Shield", Icon = "Holy Shield.jpg", Url = "https://www.wowhead.com/spell=152261/holy-shield", Description = " "},
			new Spell { Id =179, Name ="Holy Shock", Icon = "Holy Shock.jpg", Url = "https://www.wowhead.com/spell=20473/holy-shock", Description = ""},
			new Spell { Id =180, Name ="Holy Shock2", Icon = "Improved Ardent Defender.jpg", Url = "https://www.wowhead.com/spell=20473/holy-shock", Description = ""},
			new Spell { Id =181, Name ="Imbued Infusions", Icon = "Divine Inspiration.jpg", Url = "https://www.wowhead.com/spell=392961/imbued-infusions", Description = "Consuming Infusion of Light reduces the cooldown of Holy Shock by 1.0 sec."},
			new Spell { Id =182, Name ="Improved Ardent Defender", Icon = "Cleanse.jpg", Url = "https://www.wowhead.com/spell=393114/improved-ardent-defender", Description = " "},
			new Spell { Id =183, Name ="Improved Blessing of Protection", Icon = "Blessing of Protection.jpg", Url = "https://www.wowhead.com/spell=384909/improved-blessing-of-protection", Description = ""},
			new Spell { Id =184, Name ="Improved Cleanse", Icon = "Cleanse.jpg", Url = "https://www.wowhead.com/spell=393024/improved-cleanse", Description = " "},
			new Spell { Id =185, Name ="Improved Cleanse (Ret)", Icon = "Improved Cleanse (Ret).jpg", Url = "https://www.wowhead.com/spell=393024/improved-cleanse", Description = " "},
			new Spell { Id =186, Name ="Improved Holy Shield", Icon = "Holy Shield.jpg", Url = "https://www.wowhead.com/spell=393030/improved-holy-shield", Description = ""},
			new Spell { Id =187, Name ="Incandescence", Icon = "Incandescence.jpg", Url = "https://www.wowhead.com/spell=385639/incandescence", Description = " "},
			new Spell { Id =188, Name ="Inflorescence of the Sunwell", Icon = "Inflorescence of the Sunwell.jpg", Url = "https://www.wowhead.", Description = ""},
			new Spell { Id =189, Name ="Infusion of Light", Icon = "Healing Hands.jpg", Url = "https://www.wowhead.com/spell=53576/infusion-of-light", Description = " "},
			new Spell { Id =190, Name ="Infusion of Light2", Icon = "Inquisitor's Ire.jpg", Url = "https://www.wowhead.com/spell=53576/infusion-of-light", Description = " "},
			new Spell { Id =191, Name ="Inmost Light", Icon = "Shining Light.jpg", Url = "https://www.wowhead.com/spell=405757/inmost-light", Description = "Eye of Tyr deals 300% increased damage and has 33% reduced cooldown."},
			new Spell { Id =192, Name ="Inquisitor's Ire", Icon = "Inspiring Vanguard.jpg", Url = "https://www.wowhead.com/spell=403975/inquisitors-ire", Description = ""},
			new Spell { Id =193, Name ="Inspired Guard", Icon = "Divine Protection.jpg", Url = "https://www.wowhead.com/spell=469439/inspired-guard", Description = ""},
			new Spell { Id =194, Name ="Inspiring Vanguard", Icon = "Grand Crusader.jpg", Url = "https://www.wowhead.com/spell=393022/inspiring-vanguard", Description = " "},
			new Spell { Id =195, Name ="Judge, Jury and Executioner", Icon = "Judge, Jury and Executioner.jpg", Url = "https://www.wowhead.com/spell=405607/judge-jury-and-executioner", Description = ""},
			new Spell { Id =196, Name ="Judgment", Icon = "Judgment.jpg", Url = "https://www.wowhead.com/spell=20271/judgment", Description = " "},
			new Spell { Id =197, Name ="Judgment of Justice", Icon = "Judgment of Justice.jpg", Url = "https://www.wowhead.com/spell=403495/judgment-of-justice", Description = "Judgment deals 10% increased damage and increases your movement speed by 10% for 5 sec.\r\n\r\nIf you have Greater Judgment, Judgment slows enemies by 30% for 8 sec."},
			new Spell { Id =198, Name ="Judgment of Light", Icon = "Judgment of Light.jpg", Url = "https://www.wowhead.com/spell=183778/judgment-of-light", Description = " "},
			new Spell { Id =199, Name ="Judgment of the Light", Icon = "Judgment of the Light.jpg", Url = "https://www.wowhead.com/spell=183778/judgment-of-the-light", Description = ""},
			new Spell { Id =200, Name ="Justicar's Vengeance", Icon = "Justicars Vengeance.jpg", Url = "https://www.wowhead.com/spell=215661/justicars-vengeance", Description = ""},
			new Spell { Id =201, Name ="Lay on Hands", Icon = "Lay on Hands.jpg", Url = "https://www.wowhead.com/spell=633/lay-on-hands", Description = ""},
			new Spell { Id =202, Name ="Lay on Hands2", Icon = "Light of Dawn.jpg", Url = "https://www.wowhead.com/spell=633/lay-on-hands", Description = ""},
			new Spell { Id =203, Name ="Laying Down Arms", Icon = "Laying Down Arms.jpg", Url = "https://www.wowhead.com/spell=432866/laying-down-arms", Description = "When an Armament fades from you, the cooldown of Lay on Hands is reduced by 15.0 sec and you gain Infusion of Light."},
			new Spell { Id =204, Name ="Laying Down Arms2", Icon = "Laying Down Arms.jpg", Url = "https://www.wowhead.com/spell=432866/laying-down-arms", Description = "When an Armament fades from you, the cooldown of Lay on Hands is reduced by 15.0 sec and you gain Shining Light."},
			new Spell { Id =205, Name ="Lead the Charge", Icon = "Lead the Charge.jpg", Url = "https://www.wowhead.com/spell=469780/lead-the-charge", Description = ""},
			new Spell { Id =206, Name ="Liberation", Icon = "Shining Light.jpg", Url = "https://www.wowhead.com/spell=461287/liberation", Description = ""},
			new Spell { Id =207, Name ="Light of Dawn", Icon = "Light of Dawn.jpg", Url = "https://www.wowhead.com/spell=85222/light-of-dawn", Description = " "},
			new Spell { Id =208, Name ="Light of Dawn2", Icon = "Lightforged Blessing.jpg", Url = "https://www.wowhead.com/spell=85222/light-of-dawn", Description = " "},
			new Spell { Id =209, Name ="Light of the Martyr", Icon = "Light of the Martyr.jpg", Url = "https://www.wowhead.com/spell=183998/light-of-the-martyr", Description = " "},
			new Spell { Id =210, Name ="Light of the Protector", Icon = "Light of the Protector.jpg", Url = "https://www.wowhead.com/spell=184092/light-of-the-protector", Description = " "},
			new Spell { Id =211, Name ="Light of the Titans", Icon = "Lights Conviction.jpg", Url = "https://www.wowhead.com/spell=378762/light-of-the-titans", Description = " "},
			new Spell { Id =212, Name ="Lightbearer", Icon = "Lightbearer.jpg", Url = "https://www.wowhead.com/spell=469416/lightbearer", Description = " "},
			new Spell { Id =213, Name ="Lightbringer's Radiance", Icon = "Lightbringer's Radiance.jpg", Url = "https://www.wowhead.com/spell=405767/lightbringers-radiance", Description = ""},
			new Spell { Id =214, Name ="Lightforged Blessing", Icon = "Lightforged Blessing.jpg", Url = "https://www.wowhead.com/spell=403479/lightforged-blessing", Description = ""},
			new Spell { Id =215, Name ="Lightforged Blessing2", Icon = "Light's Countenance.jpg", Url = "", Description = ""},
			new Spell { Id =216, Name ="Light's Celerity", Icon = "Light's Celerity.jpg", Url = "https://www.wowhead.com/spell=403698/lights-celerity", Description = " "},
			new Spell { Id =217, Name ="Light's Celerity2", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=403698/lights-celerity", Description = ""},
			new Spell { Id =218, Name ="Light's Conviction", Icon = "Lights Conviction.jpg", Url = "https://www.wowhead.com/spell=414073/lights-conviction", Description = ""},
			new Spell { Id =219, Name ="Light's Countenance", Icon = "Lights Countenance.jpg", Url = "https://www.wowhead.com/spell=469325/lights-countenance", Description = " "},
			new Spell { Id =220, Name ="Light's Deliverance", Icon = "Lights Deliverance.jpg", Url = "https://www.wowhead.com/spell=425518/lights-deliverance", Description = " "},
			new Spell { Id =221, Name ="Light's Guidance", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=427445/lights-guidance", Description = " "},
			new Spell { Id =222, Name ="Light's Hammer", Icon = "Morning Star.jpg", Url = "https://www.wowhead.com/spell=114158/lights-hammer", Description = ""},
			new Spell { Id =223, Name ="Light's Protection", Icon = "Lights Protection.jpg", Url = "https://www.wowhead.com/spell=416799/lights-protection", Description = "Your allies with Glimmer of Light take 10% reduced damage, split evenly among them."},
			new Spell { Id =224, Name ="Light's Revocation", Icon = "Divine Shield.jpg", Url = "https://www.wowhead.com/spell=146956/lights-revocation", Description = ""},
			new Spell { Id =225, Name ="Luminosity", Icon = "Obduracy.jpg", Url = "https://www.wowhead.com/spell=431402/luminosity", Description = ""},
			new Spell { Id =226, Name ="Merciful Auras", Icon = "Merciful Auras.jpg", Url = "https://www.wowhead.com/spell=385414/merciful-auras", Description = ""},
			new Spell { Id =227, Name ="Moment of Compassion", Icon = "Flash of Light.jpg", Url = "https://www.wowhead.com/spell=407236/moment-of-compassion", Description = "Your Flash of Light heals for an additional 50% when cast on a target affected by your Beacon of Light."},
			new Spell { Id =228, Name ="Moment of Compassion2", Icon = "Penitence.jpg", Url = "https://www.wowhead.com/spell=407236/moment-of-compassion", Description = ""},
			new Spell { Id =229, Name ="Moment of Glory", Icon = "Moment of Glory.jpg", Url = "https://www.wowhead.com/spell=327193/moment-of-glory", Description = ""},
			new Spell { Id =230, Name ="Morning Star", Icon = "Reclamation.jpg", Url = "https://www.wowhead.com/spell=431482/morning-star", Description = ""},
			new Spell { Id =231, Name ="Obduracy", Icon = "Obduracy.jpg", Url = "https://www.wowhead.com/spell=385427/obduracy", Description = ""},
			new Spell { Id =232, Name ="Of Dusk and Dawn", Icon = "Light of Dawn.jpg", Url = "https://www.wowhead.com/spell=385125/of-dusk-and-dawn", Description = ""},
			new Spell { Id =233, Name ="Overflowing Light", Icon = "Unbreakable Spirit.jpg", Url = "https://www.wowhead.com/spell=461244/overflowing-light", Description = ""},
			new Spell { Id =234, Name ="Penitence", Icon = "Light of the Martyr.jpg", Url = "https://www.wowhead.com/spell=403026/penitence", Description = ""},
			new Spell { Id =235, Name ="Power of the Silver Hand", Icon = "Power of the Silver Hand.jpg", Url = "https://www.wowhead.com/spell=200294/power-of-the-silver-hand", Description = " "},
			new Spell { Id =236, Name ="Protection of Tyr", Icon = "Aura Mastery.jpg", Url = "https://www.wowhead.com/spell=200430/protection-of-tyr", Description = "Aura Mastery also increases all healing received by party or raid members within 40 yards by 10%."},
			new Spell { Id =237, Name ="Punishment", Icon = "Rebuke.jpg", Url = "https://www.wowhead.com/spell=403537/punishment", Description = ""},
			new Spell { Id =238, Name ="Quickened Invocation", Icon = "Bulwark of Order.jpg", Url = "https://www.wowhead.com/spell=379391/quickened-invocation", Description = ""},
			new Spell { Id =239, Name ="Radiant Glory", Icon = "Radiant Glory.jpg", Url = "https://www.wowhead.com/spell=405757/radiant-glory", Description = " "},
			new Spell { Id =240, Name ="Rebuke", Icon = "Rebuke.jpg", Url = "https://www.wowhead.com/spell=96231/rebuke", Description = " "},
			new Spell { Id =241, Name ="Reclamation", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=415364/reclamation", Description = " Holy Shock and Crusader Strike refund up to 10% of their Mana cost and deal up to 50% more healing or damage,  based on the target's missing health."},
			new Spell { Id =242, Name ="Reclamation (PvP)", Icon = "Reclamation (PvP).jpg", Url = "https://www.wowhead.com/spell=415364/reclamation", Description = ""},
			new Spell { Id =243, Name ="Reclamation2", Icon = "Rush of Light.jpg", Url = "https://www.wowhead.com/spell=415364/reclamation", Description = " "},
			new Spell { Id =244, Name ="Recompense", Icon = "Recompense.jpg", Url = "https://www.wowhead.com/spell=385427/recompense", Description = ""},
			new Spell { Id =245, Name ="Redoubt", Icon = "Redoubt.jpg", Url = "https://www.wowhead.com/spell=280373/redoubt", Description = ""},
			new Spell { Id =246, Name ="Refining Fire", Icon = "Refining Fire.jpg", Url = "https://www.wowhead.com/spell=469882/refining-fire", Description = "Enemies struck by Avenger's Shield burn with holy fire, suffering (57.75% of Attack power) Radiant damage over 5 sec."},
			new Spell { Id =247, Name ="Relentless Inquisitor", Icon = "Relentless Inquisitor.jpg", Url = "https://www.wowhead.com/spell=376996/relentless-inquisitor", Description = ""},
			new Spell { Id =248, Name ="Repentance", Icon = "Repentance.jpg", Url = "https://www.wowhead.com/spell=20066/repentance", Description = ""},
			new Spell { Id =249, Name ="Resolute Defender", Icon = "Veneration.jpg", Url = "https://www.wowhead.com/spell=385422/resolute-defender", Description = ""},
			new Spell { Id =250, Name ="Resplendent Light", Icon = "Resplendent Light.jpg", Url = "https://www.wowhead.com/spell=392902/resplendent-light", Description = ""},
			new Spell { Id =251, Name ="Resplendent Light (Ret)", Icon = "Resplendent Light (Ret).jpg", Url = "https://www.wowhead.com/spell=383254/resplendent-light", Description = ""},
			new Spell { Id =252, Name ="Resplendent Light2", Icon = "Sacrosanct Crusade.jpg", Url = "https://www.wowhead.com/spell=392902/resplendent-light", Description = " "},
			new Spell { Id =253, Name ="Righteous Cause", Icon = "Righteous Cause.jpg", Url = "https://www.wowhead.com/spell=405686/righteous-cause", Description = " "},
			new Spell { Id =254, Name ="Righteous Judgment", Icon = "Shake the Heavens.jpg", Url = "https://www.wowhead.com/spell=414113/righteous-judgment", Description = ""},
			new Spell { Id =255, Name ="Righteous Protection", Icon = "Blessing of Spellwarding.jpg", Url = "https://www.wowhead.com/spell=469321/righteous-protection", Description = "Blessing of Sacrifice now removes and prevents all Poison and Disease effects."},
			new Spell { Id =256, Name ="Righteous Protector", Icon = "Shield of Vengeance.jpg", Url = "https://www.wowhead.com/spell=204074/righteous-protector", Description = ""},
			new Spell { Id =257, Name ="Righteous Verdict", Icon = "Final Verdict.jpg", Url = "https://www.wowhead.com/spell=267610/righteous-verdict", Description = ""},
			new Spell { Id =258, Name ="Rising Sunlight", Icon = "Rising Sunlight.jpg", Url = "https://www.wowhead.com/spell=461250/rising-sunlight", Description = ""},
			new Spell { Id =259, Name ="Rite of Sanctification", Icon = "Rite of Sanctification.jpg", Url = "https://www.wowhead.com/spell=433568/rite-of-sanctification", Description = ""},
			new Spell { Id =260, Name ="Rule of Law", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=214202/rule-of-law", Description = ""},
			new Spell { Id =261, Name ="Rule of Law2", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=214202/rule-of-law", Description = " "},
			new Spell { Id =262, Name ="Rush of Light", Icon = "Rush of Light.jpg", Url = "https://www.wowhead.com/spell=407067/rush-of-light", Description = ""},
			new Spell { Id =263, Name ="Sacred Strength", Icon = "Searing Light.jpg", Url = "https://www.wowhead.com/spell=469337/sacred-strength", Description = " "},
			new Spell { Id =264, Name ="Sacrifice of the Just", Icon = "Blessing of Sacrifice.jpg", Url = "https://www.wowhead.com/spell=384820/sacrifice-of-the-just", Description = ""},
			new Spell { Id =265, Name ="Sacrosanct Crusade", Icon = "Sacrosanct Crusade.jpg", Url = "https://www.wowhead.com/spell=431730/sacrosanct-crusade", Description = " "},
			new Spell { Id =266, Name ="Sanctification", Icon = "Power of the Silver Hand.jpg", Url = "https://www.wowhead.com/spell=432977/sanctification", Description = "Casting Judgment increases the damage of Empyrean Hammer by 10% for 10 sec.Multiple applications may overlap."},
			new Spell { Id =267, Name ="Sanctified Ground (Ret)", Icon = "Sanctified Ground (Ret).jpg", Url = "https://www.wowhead.com/spell=204054/sanctified-ground", Description = ""},
			new Spell { Id =268, Name ="Sanctified Plates", Icon = "Sanctified Plates.jpg", Url = "https://www.wowhead.com/spell=394081/sanctified-plates", Description = " "},
			new Spell { Id =269, Name ="Sanctified Plates2", Icon = "Sanctified Wrath.jpg", Url = "https://www.wowhead.com/spell=394081/sanctified-plates", Description = ""},
			new Spell { Id =270, Name ="Sanctified Plates3", Icon = "Sanctified Wrath.jpg", Url = "https://www.wowhead.com/spell=394081/sanctified-plates", Description = ""},
			new Spell { Id =271, Name ="Sanctified Wrath", Icon = "Sanctified Wrath.jpg", Url = "https://www.wowhead.com/spell=53376/sanctified-wrath", Description = " "},
			new Spell { Id =272, Name ="Sanctuary", Icon = "Consecration.jpg", Url = "https://www.wowhead.com/spell=379021/sanctuary", Description = "Consecration's benefits persist for 4 seconds after you leave it."},
			new Spell { Id =273, Name ="Saved by the Light", Icon = "Saved by the Light.jpg", Url = "https://www.wowhead.com/spell=321136/shining-light", Description = ""},
			new Spell { Id =274, Name ="Seal of Charity", Icon = "Gleaming Rays.jpg", Url = "https://www.wowhead.com/spell=384815/seal-of-charity", Description = " "},
			new Spell { Id =275, Name ="Seal of Clarity", Icon = "Seal of Clarity.jpg", Url = "https://www.wowhead.com/spell=385428/seal-of-clarity", Description = " "},
			new Spell { Id =276, Name ="Seal of Clarity2", Icon = "Seal of Clarity.jpg", Url = "https://www.wowhead.com/spell=385428/seal-of-clarity", Description = ""},
			new Spell { Id =277, Name ="Seal of Mercy", Icon = "Seal of Mercy.jpg", Url = "https://www.wowhead.com/spell=385427/seal-of-mercy", Description = " "},
			new Spell { Id =278, Name ="Seal of Mercy (Ret)", Icon = "Seal of Mercy (Ret).jpg", Url = "https://www.wowhead.com/spell=385427/seal-of-mercy", Description = " "},
			new Spell { Id =279, Name ="Seal of Mercy2", Icon = "Seal of Mercy.jpg", Url = "https://www.wowhead.com/spell=385427/seal-of-mercy", Description = ""},
			new Spell { Id =280, Name ="Seal of Might", Icon = "Seal of Might.jpg", Url = "https://www.wowhead.com/spell=385450/seal-of-might", Description = ""},
			new Spell { Id =281, Name ="Seal of Order", Icon = "Seal of Order.jpg", Url = "https://www.wowhead.com/spell=385425/seal-of-order", Description = " "},
			new Spell { Id =282, Name ="Seal of Order2", Icon = "Seal of Order.jpg", Url = "https://www.wowhead.com/spell=385425/seal-of-order", Description = ""},
			new Spell { Id =283, Name ="Seal of Reprisal", Icon = "Seal of Reprisal.jpg", Url = "https://www.wowhead.com/spell=377053/seal-of-reprisal", Description = "Your [Blessed Hammer] [Hammer of the Righteous / Crusader Strike] deals 20% increased damage."},
			new Spell { Id =284, Name ="Seal of the Crusader", Icon = "SotC.jpg", Url = "https://www.wowhead.com/spell=416770/seal-of-the-crusader", Description = ""},
			new Spell { Id =285, Name ="Seal of the Crusader2", Icon = "Eye for an Eye.jpg", Url = "https://www.wowhead.com/spell=416770/seal-of-the-crusader", Description = ""},
			new Spell { Id =286, Name ="Seal of Wrath", Icon = "Seal of Wrath.jpg", Url = "https://www.wowhead.com/spell=405798/seal-of-wrath", Description = " "},
			new Spell { Id =287, Name ="Sealed Verdict", Icon = "Sealed Verdict.jpg", Url = "https://www.wowhead.com/spell=385633/sealed-verdict", Description = ""},
			new Spell { Id =288, Name ="Searing Judgment", Icon = "Searing Judgment.jpg", Url = "https://www.wowhead.com/spell=403530/searing-judgment", Description = ""},
			new Spell { Id =289, Name ="Searing Light", Icon = "Searing Light.jpg", Url = "https://www.wowhead.com/spell=403221/searing-light", Description = " "},
			new Spell { Id =290, Name ="Searing Light2", Icon = "Sun Sear.jpg", Url = "https://www.wowhead.com/spell=403221/searing-light", Description = " "},
			new Spell { Id =291, Name ="Second Sunrise", Icon = "Divine Guidance.jpg", Url = "https://www.wowhead.com/spell=200482/second-sunrise", Description = ""},
			new Spell { Id =292, Name ="Seething Flames", Icon = "Seething Flames.jpg", Url = "https://www.wowhead.com/spell=405355/seething-flames", Description = ""},
			new Spell { Id =293, Name ="Selfless Healer", Icon = "Selfless Healer.jpg", Url = "https://www.wowhead.com/spell=85804/selfless-healer", Description = ""},
			new Spell { Id =294, Name ="Sentinel", Icon = "Sentinel.jpg", Url = "https://www.wowhead.com/spell=389539/sentinel", Description = " "},
			new Spell { Id =295, Name ="Seraphim", Icon = "Seraphim.jpg", Url = "https://www.wowhead.com/spell=152262/seraphim", Description = " "},
			new Spell { Id =296, Name ="Shake the Heavens", Icon = "Shake the Heavens.jpg", Url = "https://www.wowhead.com/spell=431533/shake-the-heavens", Description = " "},
			new Spell { Id =297, Name ="Shared Resolve", Icon = "Devotion Aura.jpg", Url = "https://www.wowhead.com/spell=432821/shared-resolve", Description = ""},
			new Spell { Id =298, Name ="Shield of the Righteous", Icon = "Shield of the Righteous.jpg", Url = "https://www.wowhead.com/spell=53600/shield-of-the-righteous", Description = ""},
			new Spell { Id =299, Name ="Shield of Vengeance", Icon = "Shield of Vengeance.jpg", Url = "https://www.wowhead.com/spell=184662/shield-of-vengeance", Description = " "},
			new Spell { Id =300, Name ="Shielding Words", Icon = "Shielding Words.jpg", Url = "https://www.wowhead.com/spell=379010/shielding-words", Description = " "},
			new Spell { Id =301, Name ="Shining Light", Icon = "Shining Light.jpg", Url = "https://www.wowhead.com/spell=327510/shining-light", Description = " "},
			new Spell { Id =302, Name ="Shining Righteousness", Icon = "Divine Guidance.jpg", Url = "https://www.wowhead.com/spell=414445/shining-righteousness", Description = "[Denounce / Shield of the Righteous] deals (128% of Spell power) damage to its first target struck. Every 4 [Denounce: Denounces / Shields of the Righteous] make your next Word of Glory or Light of Dawn cost no Holy Power."},
			new Spell { Id =303, Name ="Soaring Shield", Icon = "Soaring Shield.jpg", Url = "https://www.wowhead.com/spell=378457/soaring-shield", Description = "Avenger's Shield jumps to 2 additional targets."},
			new Spell { Id =304, Name ="Solar Grace", Icon = "Truth Prevails.jpg", Url = "https://www.wowhead.com/spell=431404/solar-grace", Description = " "},
			new Spell { Id =305, Name ="Solidarity", Icon = "Guardian of Ancient Kings.jpg", Url = "https://www.wowhead.com/spell=432802/solidarity", Description = "If you bestow an Armament upon an ally, you also gain its benefits. If you bestow an Armament upon yourself, a nearby ally also gains its benefits."},
			new Spell { Id =306, Name ="Stand Against Evil", Icon = "Stand Against Evil.jpg", Url = "https://www.wowhead.com/spell=469317/stand-against-evil", Description = "Turn Evil now affects 5 additional enemies."},
			new Spell { Id =307, Name ="Stoicism", Icon = "Stoicism.jpg", Url = "https://www.wowhead.com/spell=384820/divine-judgement", Description = ""},
			new Spell { Id =308, Name ="Strength in Adversity", Icon = "Eye for an Eye.jpg", Url = "https://www.wowhead.com/spell=393071/strength-in-adversity", Description = ""},
			new Spell { Id =309, Name ="Sun Sear", Icon = "Sun Sear.jpg", Url = "https://www.wowhead.com/spell=431413/sun-sear", Description = " "},
			new Spell { Id =310, Name ="Sun's Avatar", Icon = "Suns Avatar.jpg", Url = "https://www.wowhead.com/spell=431425/suns-avatar", Description = ""},
			new Spell { Id =311, Name ="Templar Slash", Icon = "Templar Slash.jpg", Url = "https://www.wowhead.com/spell=407479/templar-slash", Description = " "},
			new Spell { Id =312, Name ="Templar Strike", Icon = "Templar Strike.jpg", Url = "https://www.wowhead.com/spell=407480/templar-strike", Description = ""},
			new Spell { Id =313, Name ="Templar Strikes", Icon = "Templar Strikes.jpg", Url = "https://www.wowhead.com/spell=407480/templar-strikes", Description = " "},
			new Spell { Id =314, Name ="Templar's Verdict", Icon = "Templar's Verdict.jpg", Url = "https://www.wowhead.com/spell=85256/templars-verdict", Description = " "},
			new Spell { Id =315, Name ="Tirion's Devotion", Icon = "Tirions Devotion.jpg", Url = "https://www.wowhead.com/spell=414720/tirions-devotion", Description = " "},
			new Spell { Id =316, Name ="Touch of Light", Icon = "Touch of Light.jpg", Url = "https://www.wowhead.com/spell=386922/touch-of-light", Description = ""},
			new Spell { Id =317, Name ="Tower of Radiance", Icon = "Executioners Will.jpg", Url = "https://www.wowhead.com/spell=231642/tower-of-radiance", Description = " "},
			new Spell { Id =318, Name ="Truth Prevails", Icon = "Truth Prevails.jpg", Url = "https://www.wowhead.com/spell=461273/truth-prevails", Description = "Judgment heals you for (240% of Spell power) and its mana cost is reduced by 30%. 50% of overhealing from this effect is transferred onto 2 allies within 40 yds."},
			new Spell { Id =319, Name ="Truth's Wake", Icon = "Truth's Wake.jpg", Url = "https://www.wowhead.com/spell=406154/truths-wake", Description = ""},
			new Spell { Id =320, Name ="Truth's Wake2", Icon = "Truth's Wake.jpg", Url = "https://www.wowhead.com/spell=406154/truths-wake", Description = ""},
			new Spell { Id =321, Name ="Turn Evil", Icon = "Turn Evil.jpg", Url = "https://www.wowhead.com/spell=10326/turn-evil", Description = " "},
			new Spell { Id =322, Name ="Tyr's Deliverance", Icon = "Tyrs Deliverance.jpg", Url = "https://www.wowhead.com/spell=200652/tyrs-deliverance", Description = " "},
			new Spell { Id =323, Name ="Tyr's Deliverance (PvP)", Icon = "Tyr's Deliverance (PvP).jpg", Url = "https://www.wowhead.com/spell=199454/tyrs-deliverance", Description = " "},
			new Spell { Id =324, Name ="Tyr's Deliverance2", Icon = "Aegis of Light.jpg", Url = "https://www.wowhead.com/spell=200652/tyrs-deliverance", Description = " "},
			new Spell { Id =325, Name ="Tyr's Enforcer", Icon = "Morning Star.jpg", Url = "https://www.wowhead.com/spell=406570/tyrs-enforcer", Description = ""},
			new Spell { Id =326, Name ="Unbound Freedom", Icon = "Blessing of Freedom.jpg", Url = "https://www.wowhead.com/spell=305394/unbound-freedom", Description = " "},
			new Spell { Id =327, Name ="Unbreakable Spirit", Icon = "Unbreakable Spirit.jpg", Url = "https://www.wowhead.com/spell=114154/unbreakable-spirit", Description = ""},
			new Spell { Id =328, Name ="Undisputed Ruling", Icon = "Judgment.jpg", Url = "https://www.wowhead.com/spell=432626/undisputed-ruling", Description = ""},
			new Spell { Id =329, Name ="Unending Light", Icon = "Unending Light.jpg", Url = "https://www.wowhead.com/spell=405719/unending-light", Description = ""},
			new Spell { Id =330, Name ="Unrelenting Charger", Icon = "Unrelenting Charger.jpg", Url = "https://www.wowhead.com/spell=432990/unrelenting-charger", Description = ""},
			new Spell { Id =331, Name ="Unwavering Spirit", Icon = "Aegis of Protection.jpg", Url = "https://www.wowhead.com/spell=392911/unwavering-spirit", Description = " "},
			new Spell { Id =332, Name ="Uther's Counsel", Icon = "Uthers Counsel.jpg", Url = "https://www.wowhead.com/spell=378425/uthers-counsel", Description = "Your Lay on Hands, Divine Shield, Blessing of Protection, and Blessing of Spellwarding have 15% reduced cooldown."},
			new Spell { Id =333, Name ="Valiance", Icon = "Valiance.jpg", Url = "https://www.wowhead.com/spell=432919/valiance", Description = "Consuming Infusion of Light reduces the cooldown of Holy Armaments by 3.0 sec."},
			new Spell { Id =334, Name ="Valiance2", Icon = "Valiance.jpg", Url = "https://www.wowhead.com/spell=432919/valiance", Description = "Consuming Shining Light reduces the cooldown of Holy Armaments by 3.0 sec."},
			new Spell { Id =335, Name ="Vanguard's Momentum", Icon = "Obduracy.jpg", Url = "https://www.wowhead.com/spell=405065/vanguards-momentum", Description = " "},
			new Spell { Id =336, Name ="Veneration", Icon = "Veneration.jpg", Url = "https://www.wowhead.com/spell=392902/veneration", Description = ""},
			new Spell { Id =337, Name ="Vengeful Wrath", Icon = "Hammer of Wrath.jpg", Url = "https://www.wowhead.com/spell=403592/vengeful-wrath", Description = ""},
			new Spell { Id =338, Name ="Wake of Ashes", Icon = "Wake of Ashes.jpg", Url = "https://www.wowhead.com/spell=255937/wake-of-ashes", Description = " "},
			new Spell { Id =339, Name ="Will of the Dawn", Icon = "Judgment of Light.jpg", Url = "https://www.wowhead.com/spell=431462/will-of-the-dawn", Description = ""},
			new Spell { Id =340, Name ="Wrathful Descent", Icon = "Wrathful Descent.jpg", Url = "https://www.wowhead.com/spell=431551/wrathful-descent", Description = ""},
			new Spell { Id =341, Name ="Wrench Evil", Icon = "Wrench Evil.jpg", Url = "https://www.wowhead.com/spell=339292/wrench-evil", Description = "Turn Evil's cast time is reduced by 40.0%, and its range is increased by 10 yds."},
			new Spell { Id =342, Name ="Zeal", Icon = "Zeal.jpg", Url = "https://www.wowhead.com/spell=269569/zeal", Description = " "},
			new Spell { Id =343, Name ="Zealot's Paragon", Icon = "Moment of Glory.jpg", Url = "https://www.wowhead.com/spell=391142/zealots-paragon", Description = ""},
			new Spell { Id =344, Name ="Zealous Vindication", Icon = "Zealous Vindication.jpg", Url = "https://www.wowhead.com/spell=431463/zealous-vindication", Description = "Hammer of Light instantly calls down 2 Empyrean Hammers on your target when it is cast."},
			new Spell { Id =345, Name ="Divine Auxiliary", Icon = "Divine Auxiliary.jpg", Url = "https://www.wowhead.com/spell=406158/divine-auxiliary", Description = "Final Reckoning and Execution Sentence grant 3 Holy Power."},
			new Spell { Id =346, Name ="Heart of the Crusader", Icon = "Heart of the Crusader.jpg", Url = "https://www.wowhead.com/spell=406154/heart-of-the-crusader", Description = "Crusader Strike and auto-attacks deal 10% increased damage and deal 10% increased critical strike damage." },
			new Spell { Id =347, Name ="Boundless Judgment", Icon = "Boundless Judgment.jpg", Url = "https://www.wowhead.com/spell=405278/boundless-judgment", Description = "Judgment generates 1 additional Holy Power and has a 50% increased chance to trigger Mastery: Highlord's Judgment." },
			new Spell { Id =348, Name ="Zealot's Fervor", Icon = "Eye for an Eye.jpg", Url = "https://www.wowhead.com/spell=403509/zealots-fervor", Description = "\r\nAuto-attack speed increased by 20%.\r\n"},
			new Spell { Id =349, Name ="Jurisdiction", Icon = "Rule of Law.jpg", Url = "https://www.wowhead.com/spell=204979/jurisdiction", Description = "Increase the range of Blade of Justice and Hammer of Justice by 10 yds, and radius of Divine Storm by 4 yds." },
			new Spell { Id =350, Name ="Tempest of the Lightbringer", Icon = "Divine Storm.jpg", Url = "https://www.wowhead.com/spell=337257/tempest-of-the-lightbringer", Description = "Divine Storm projects an additional wave of light, striking all enemies up to 20 yards in front of you for 20% of Divine Storm's damage." },
			new Spell { Id =351, Name ="Guided Prayer", Icon = "Veneration.jpg", Url = "https://www.wowhead.com/spell=404357/guided-prayer", Description = "When your health is brought below 25%, you instantly cast a free Word of Glory at 60% effectiveness on yourself.\r\n\r\nCannot occur more than once every 60 sec." },
			new Spell { Id =352, Name ="Art of War", Icon = "Truth Prevails.jpg", Url = "https://www.wowhead.com/spell=461273/truth-prevails", Description = "Judgment heals you for (240% of Spell power) and its mana cost is reduced by 30%. 50% of overhealing from this effect is transferred onto 2 allies within 40 yds." },
			new Spell { Id =353, Name ="Swift Justice", Icon = "Blessed Calling.jpg", Url = "https://www.wowhead.com/spell=383228/swift-justice", Description = "Reduces the cooldown of Judgment by 2 sec and Crusader Strike by 2 sec." },
			new Spell { Id =354, Name ="Judgement of Justice", Icon = "Highlords Wrath.jpg", Url = "https://www.wowhead.com/wotlk/spell=53407/judgement-of-justice", Description = "Unleashes the energy of a Seal spell to judge an enemy for 20 sec, preventing them from fleeing and limiting their movement speed.  Refer to individual Seals for additional Judgement effect.  Only one Judgement per Paladin can be active at any one time." },
			new Spell { Id =355, Name ="Mastery: Lightbringer", Icon = "inv_hammer_04.jpg", Url = "https://www.wowhead.com/spell=183997/mastery-lightbringer", Description = "Increases healing done by up to 12.00%, based on the proximity of your target." },
			new Spell { Id =356, Name ="Solidarity", Icon = "inv_hammer_04.jpg", Url = "https://www.wowhead.com/spell=432802/solidarity", Description = "\nIf you bestow an Armament upon an ally, you also gain its benefits.\n\nIf you bestow an Armament upon yourself, a nearby ally also gains its benefits." },
			new Spell { Id =357, Name ="Shared Resolve", Icon = "inv_hammer_04.jpg", Url = "https://www.wowhead.com/spell=432803/empyrean-power", Description = "Your abilities have a chance to grant you Empyrean Power, increasing your damage and healing by 5% for 10 sec. Empyrean Power can stack up to 3 times." },
			new Spell { Id =358, Name ="Word of Glory", Icon = "Word of Glory.jpg", Url = "https://www.wowhead.com/spell=85673/word-of-glory", Description = "Your abilities have a chance to grant you Empyrean Power, increasing your damage and healing by 5% for 10 sec. Empyrean Power can stack up to 3 times." }
			};

			await db.Spells.AddRangeAsync(spells);
			await db.SaveChangesAsync();
		}
	}

