BEGIN;
CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Description" varchar(2000) NOT NULL DEFAULT '',
    "ParentId" integer REFERENCES "Categories"("Id") ON DELETE RESTRICT,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsArchived" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "Version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_ActiveSiblingName" ON "Categories" (COALESCE("ParentId", 0), lower("Name")) WHERE NOT "IsDeleted";
CREATE TABLE IF NOT EXISTS "CategoryRevisions" (
    "Id" uuid PRIMARY KEY,
    "CategoryId" integer NOT NULL REFERENCES "Categories"("Id") ON DELETE RESTRICT,
    "Version" integer NOT NULL,
    "Action" varchar(30) NOT NULL,
    "Actor" varchar(256) NOT NULL,
    "Snapshot" text NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryRevisions_CategoryId_Version" ON "CategoryRevisions" ("CategoryId", "Version");
ALTER TABLE "Spells" ADD COLUMN IF NOT EXISTS "CategoryId" integer REFERENCES "Categories"("Id") ON DELETE RESTRICT;
ALTER TABLE "Items" ADD COLUMN IF NOT EXISTS "CategoryId" integer REFERENCES "Categories"("Id") ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Spells_CategoryId" ON "Spells" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_Items_CategoryId" ON "Items" ("CategoryId");
COMMIT;
