BEGIN;
CREATE TABLE IF NOT EXISTS "NavigationLinks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Description" varchar(2000) NOT NULL DEFAULT '',
    "Href" varchar(2048) NOT NULL DEFAULT '/',
    "Location" varchar(20) NOT NULL DEFAULT 'primary' CHECK ("Location" IN ('primary','utility')),
    "OpenNewTab" boolean NOT NULL DEFAULT false,
    "ParentId" integer REFERENCES "NavigationLinks"("Id") ON DELETE RESTRICT,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsArchived" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "Version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_NavigationLinks_ActiveSiblingName" ON "NavigationLinks" ("Location", COALESCE("ParentId", 0), lower("Name")) WHERE NOT "IsDeleted";
CREATE TABLE IF NOT EXISTS "NavigationRevisions" (
    "Id" uuid PRIMARY KEY,
    "NavigationId" integer NOT NULL REFERENCES "NavigationLinks"("Id") ON DELETE RESTRICT,
    "Version" integer NOT NULL,
    "Action" varchar(30) NOT NULL,
    "Actor" varchar(256) NOT NULL,
    "Snapshot" text NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_NavigationRevisions_NavigationId_Version" ON "NavigationRevisions" ("NavigationId", "Version");
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM "NavigationLinks") THEN
INSERT INTO "NavigationLinks" ("Id","Name","Href","Location","ParentId","SortOrder") VALUES
(1,'Home','/Home/Home','primary',NULL,0),
(2,'Holy Paladin','/Holy/Overview','primary',NULL,1),
(3,'Protection Paladin','/Protection/Overview','primary',NULL,2),
(4,'Retribution Paladin','/Retribution/Overview','primary',NULL,3),
(5,'Discussion','/Discussions/Index','primary',NULL,4),
(6,'Privacy','/Home/Privacy','primary',NULL,5),
(7,'Merchandise','/Merchandise/Merchandise','utility',NULL,0),
(8,'Gear','/Holy/Gear','primary',2,0),
(9,'Talents','/Holy/Talents','primary',2,1),
(10,'Consumables','/Holy/Consumables','primary',2,2),
(11,'Rotation','/Holy/Rotation','primary',2,3),
(12,'Stats','/Holy/Stats','primary',2,4),
(13,'Gear','/Protection/Gear','primary',3,0),
(14,'Talents','/Protection/Talents','primary',3,1),
(15,'Consumables','/Protection/Consumables','primary',3,2),
(16,'Rotation','/Protection/Rotation','primary',3,3),
(17,'Stats','/Protection/Stats','primary',3,4),
(18,'Gear','/Retribution/Gear','primary',4,0),
(19,'Talents','/Retribution/Talents','primary',4,1),
(20,'Consumables','/Retribution/Consumables','primary',4,2),
(21,'Rotation','/Retribution/Rotation','primary',4,3),
(22,'Stats','/Retribution/Stats','primary',4,4);
PERFORM setval(pg_get_serial_sequence('"NavigationLinks"','Id'), (SELECT max("Id") FROM "NavigationLinks"));
END IF; END $$;
INSERT INTO "NavigationRevisions" ("Id","NavigationId","Version","Action","Actor","Snapshot","CreatedAtUtc")
SELECT gen_random_uuid(), n."Id", n."Version", 'imported', 'database-upgrade', row_to_json(n)::text, now()
FROM "NavigationLinks" n WHERE NOT EXISTS (SELECT 1 FROM "NavigationRevisions" r WHERE r."NavigationId"=n."Id");
COMMIT;
