BEGIN;
CREATE TABLE IF NOT EXISTS "ItemRarities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(50) NOT NULL,
    "Description" varchar(2000) NOT NULL DEFAULT '',
    "Color" varchar(7) NOT NULL DEFAULT '#ffffff' CHECK ("Color" ~ '^#[0-9a-fA-F]{6}$'),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsArchived" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "Version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ItemRarities_ActiveName" ON "ItemRarities" (lower("Name")) WHERE NOT "IsDeleted";
CREATE TABLE IF NOT EXISTS "RarityRevisions" (
    "Id" uuid PRIMARY KEY,
    "RarityId" integer NOT NULL REFERENCES "ItemRarities"("Id") ON DELETE RESTRICT,
    "Version" integer NOT NULL,
    "Action" varchar(30) NOT NULL,
    "Actor" varchar(256) NOT NULL,
    "Snapshot" text NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RarityRevisions_RarityId_Version" ON "RarityRevisions" ("RarityId", "Version");
ALTER TABLE "Items" ADD COLUMN IF NOT EXISTS "RarityId" integer REFERENCES "ItemRarities"("Id") ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Items_RarityId" ON "Items" ("RarityId");
INSERT INTO "ItemRarities" ("Name", "Color", "SortOrder")
SELECT name, color, position FROM (VALUES ('Poor','#9d9d9d',0), ('Common','#ffffff',1), ('Uncommon','#1eff00',2), ('Rare','#0070dd',3), ('Epic','#a335ee',4), ('Legendary','#ff8000',5), ('Artifact','#e6cc80',6), ('Heirloom','#00ccff',7)) AS defaults(name,color,position)
WHERE NOT EXISTS (SELECT 1 FROM "ItemRarities");
INSERT INTO "ItemRarities" ("Name")
SELECT min(trim(i."Quality")) FROM "Items" i WHERE NULLIF(trim(i."Quality"),'') IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM "ItemRarities" r WHERE lower(r."Name")=lower(trim(i."Quality"))) GROUP BY lower(trim(i."Quality"));
UPDATE "Items" i SET "RarityId"=r."Id", "Quality"=r."Name" FROM "ItemRarities" r
WHERE i."RarityId" IS NULL AND lower(trim(i."Quality"))=lower(r."Name") AND NOT r."IsDeleted";
INSERT INTO "RarityRevisions" ("Id", "RarityId", "Version", "Action", "Actor", "Snapshot", "CreatedAtUtc")
SELECT gen_random_uuid(), r."Id", r."Version", 'imported', 'database-upgrade', row_to_json(r)::text, now()
FROM "ItemRarities" r WHERE NOT EXISTS (SELECT 1 FROM "RarityRevisions" h WHERE h."RarityId"=r."Id");
COMMIT;
