BEGIN;
CREATE TABLE IF NOT EXISTS "GameTags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Description" varchar(2000) NOT NULL DEFAULT '',
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsArchived" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "Version" integer NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_GameTags_ActiveName" ON "GameTags" (lower("Name")) WHERE NOT "IsDeleted";
CREATE TABLE IF NOT EXISTS "TagRevisions" (
    "Id" uuid PRIMARY KEY,
    "TagId" integer NOT NULL REFERENCES "GameTags"("Id") ON DELETE RESTRICT,
    "Version" integer NOT NULL,
    "Action" varchar(30) NOT NULL,
    "Actor" varchar(256) NOT NULL,
    "Snapshot" text NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TagRevisions_TagId_Version" ON "TagRevisions" ("TagId", "Version");
ALTER TABLE "Spells" ADD COLUMN IF NOT EXISTS "TagIds" integer[] NOT NULL DEFAULT '{{}}';
ALTER TABLE "Items" ADD COLUMN IF NOT EXISTS "TagIds" integer[] NOT NULL DEFAULT '{{}}';
CREATE INDEX IF NOT EXISTS "IX_Spells_TagIds" ON "Spells" USING gin ("TagIds");
CREATE INDEX IF NOT EXISTS "IX_Items_TagIds" ON "Items" USING gin ("TagIds");
COMMIT;
